spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kanban_and_calendar
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
  liquibase:
    enabled: false
  flyway:
    baselineOnMigrate: true

# Specify the path of the OpenAPI documentation
springdoc:
  api-docs:
    path: /api-docs
# Specify the path of the Swagger UI
  swagger-ui:
    path: /swagger-ui.html
# Enable or disable Swagger UI
    enabled: true
#spring.jpa.hibernate.ddl-auto=update
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 10m
